name: Bug Report
description: Use this template for reporting a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Examples of bugs could include the following:
        - Functionality of existing components/features
        - Accessibility
        - Build process
        - Documentation
  - type: textarea
    attributes:
      label: Describe the bug
      description: Short description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide a detailed description of the steps taken to reproduce the bug.
      value: |
        1.
        2.
        3.
  - type: input
    attributes:
      label: Which browser are you using? (if relevant)
      description: Please specify the exact version if necessary.
  - type: textarea
    attributes:
      label: Additional context
