name: 🚀  Feature Request
description: Use this template for suggesting a DNA enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Examples of enhancements could include:
        - New components/features
        - Improvements to existing features
        - Updating existing code to use new Shopify API/Liquid features
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: true
      options:
        - High
        - Medium
        - Low
  - type: dropdown
    id: loe
    attributes:
      label: LOE (Level of Effort)
      multiple: true
      options:
        - High
        - Medium
        - Low
        - Unsure / Needs Discovery
  - type: textarea
    attributes:
      label: Do any existing projects forked from DNA have this feature already built out?
      description: Please link to the repo files and/or provide images of the completed feature if possible.
  - type: textarea
    attributes:
      label: Does this feature exist in any other Shopify themes or sites?
      description: Please link to the site and/or provide images of the completed feature if possible.
  - type: textarea
    attributes:
      label: Is there any specific Shopify documentation that would help in building this feature?
  - type: textarea
    attributes:
      label: Additional context
